# Generated by Django 3.2.5 on 2021-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, upload_to='audio/%Y/%m/%d', verbose_name='Голосовое'),
        ),
    ]
