# Generated by Django 3.2.5 on 2021-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, upload_to='messages/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
